title: Animation Video Clip
description: Animation Video Clip is a website that recreates a popular animation video from the game Geometry Dash using only HTML, CSS, and JavaScript.
google_analytics:
theme: jekyll-theme-hacker